#ansible vaiables

- name: Ansible variables
  hosts: localhost
  vars:
    Course: "Devops"
    Trainer: "Bhargav"
    Duration: "120HRS"
  tasks:
    - name: check variables
      ansible.builtin.debug:
        msg: "Hi iam learning the {{Course}} duration is {{Duration}} and trainer is {{Trainer}}"
