#ansible conditions

- name: ansible conditions
  hosts: localhost
  become: yes
  tasks:
    - name: check id roboshop exists
      ansible.builtin.command: id roboshop
      register: User # user is a vaiable name:
      ignore_errors: true
    - name: print the exists status code
      ansible.builtin.debug:
        msg: "Status code {{User.rc}}"
    - name: create user
      ansible.builtin.user:
        name: roboshop
      when: User.rc != 0 #condition
