- name: ping playbook
  hosts: web
  tasks:
    - name: Ping the server
      ansible.builtin.ping:
    - name: this is vaulut
      ansible.builtin.debug:
        msg: "this vault service taking variable from group_vars folder"
